compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  train_batch_size: 1
  train_micro_batch_size_per_gpu: 1
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: "cpu"
  offload_param_device: "cpu"
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 2
  "bf16": {
   "enabled": true
  }
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false